# docker-compose.dev.yml
# 构建测试环境的 Docker Compose 配置
version: '3.5'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ... 其他生产环境适用的配置

  django:
    # build: ./myproject #### 生产环境中删除
    image: 'qrkks3/tradingweb:django-${TAG}'
    environment:
      - DEBUG=False  # 确保在生产环境中关闭调试模式
      - NPM_BIN_PATH=${NPM_BIN_PATH}
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - static_volume:/code/static_cdn
      - media_volume:/code/media
    expose:
      - "8000"
    restart: always
    depends_on:
      - postgres

  nginx:
    # build: ./nginx #### 生产环境中删除
    image: 'qrkks3/tradingweb:nginx-${TAG}'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      # - /home/lighthouse/ssl/certs:/etc/ssl/certs
      # - /home/lighthouse/ssl/private:/etc/ssl/private
    environment:
      - TZ=${TZ}
    env_file:
      - .env
    depends_on:
      - django
    restart: always
    # 可能需要添加 SSL/TLS 配置

volumes:
  static_volume:
  media_volume:
  postgres_data:
