version: '3.9'

services:
  django:
    environment:
      - DEBUG=0
      - NPM_BIN_PATH="/usr/local/bin/npm"
      - TZ=Asia/Shanghai
    build: ./myproject
    volumes:
      # - ./myproject:/code
      - static_volume:/code/static # 相对于文件系统而不是相对于workdir
      - media_volume:/code/media
    ports:
      - "8000:8000"


  nginx:
    # image: nginx:1.25.3-alpine
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    environment:
      - TZ:Asia/Shanghai
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
  