# docker-compose.ci.yml
# 构建 CI 环境的 Docker Compose 配置

version: '3.9'

services:

  django:
    build: ./myproject #### 生产环境中删除
    image: 'qrkks3/tradingweb:django-${TAG}'

  nginx:
    build: ./nginx #### 生产环境中删除
    image: 'qrkks3/tradingweb:nginx-${TAG}'


