version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  django:
    build: ./myproject
    environment:
      - DEBUG=${DEBUG}
      - NPM_BIN_PATH=${NPM_BIN_PATH}
      - TZ=${TZ}
    volumes:
      - ./myproject:/code
      - static_volume:/code/static_cdn
      - media_volume:/code/media
    expose:
      - "8000"
    restart: always
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    environment:
      - TZ=${TZ}
    depends_on:
      - django
    restart: always

volumes:
  static_volume:
  media_volume:
  postgres_data:
