# Generated by Django 4.2.4 on 2023-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("country_region", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("source_webpage", models.URLField(blank=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("country_from_ip", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
