# Generated by Django 4.2.4 on 2023-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_handlers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={"verbose_name_plural": "inquiries"},
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="country_from_ip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="source_webpage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
