# Generated by Django 4.2.4 on 2023-10-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_handlers", "0002_alter_inquiry_options_alter_inquiry_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_inbox", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "notification inboxes",
            },
        ),
    ]
