# Generated by Django 4.2.4 on 2023-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_homecarouselimage_header_homecarouselimage_paragraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselimage",
            name="learn_more",
            field=models.URLField(blank=True, null=True),
        ),
    ]
