# Generated by Django 4.2.4 on 2023-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_rename_detail_socialmedia_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinformation",
            old_name="detail",
            new_name="info",
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
