# Generated by Django 4.2.4 on 2023-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_contactinformation_link_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="link",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True
            ),
        ),
    ]
