# Generated by Django 4.2.4 on 2023-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_cta_alter_homecarouselimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cta_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/cta/images"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Cta",
        ),
    ]
