# Generated by Django 4.2.4 on 2023-09-27 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="content",
        ),
    ]
