# Generated by Django 4.2.7 on 2023-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_description_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
