# Generated by Django 4.2.7 on 2023-11-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_custom_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="custom_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
