# Generated by Django 4.2.7 on 2023-12-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_productimage_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
