# Generated by Django 4.2.7 on 2023-12-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
