# Generated by Django 4.2.7 on 2023-12-13 01:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_product_code_alter_category_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_code",
        ),
        migrations.AddField(
            model_name="product",
            name="detail_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
