# Generated by Django 4.2.7 on 2023-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_remove_productimage_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Size of the image file in kilobytes (KB)"
            ),
        ),
    ]
