# Generated by Django 4.2.7 on 2023-12-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_alter_productimage_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_for_display",
            field=models.BooleanField(default=True),
        ),
    ]
