# Generated by Django 4.2.7 on 2023-12-15 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_productimage_is_for_display"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_order",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model",
        ),
        migrations.RemoveField(
            model_name="product",
            name="payment_terms",
        ),
        migrations.RemoveField(
            model_name="product",
            name="port",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_capacity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="transport_package",
        ),
    ]
