# Generated by Django 4.2.4 on 2023-09-27 14:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
