# Generated by Django 4.2.4 on 2023-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_category_blog_created_at_blog_custom_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["custom_order", "is_featured", "-id"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
