version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static:/staticfiles
      - sqlite:/db.sqlite3
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: