# Generated by Django 4.2.7 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "form_handlers",
            "0008_remove_inquiry_custom_order_remove_inquiry_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationinbox",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
