# Generated by Django 4.2.4 on 2023-09-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecarouselimage",
            name="header",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homecarouselimage",
            name="paragraph",
            field=models.TextField(blank=True, null=True),
        ),
    ]
