# Generated by Django 4.2.4 on 2023-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_rename_detail_contactinformation_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
