# Generated by Django 4.2.4 on 2023-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_contactinformation_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="link_template",
            field=models.CharField(
                blank=True,
                help_text="Use {{contact_info}} to insert contact info",
                max_length=200,
                null=True,
            ),
        ),
    ]
