# Generated by Django 4.2.7 on 2023-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0016_banner_delete_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homecarouselimage",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="custom_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
