# Generated by Django 4.2.7 on 2023-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0018_alter_banner_custom_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="link_template",
            field=models.CharField(
                blank=True,
                help_text="Use {info} to insert contact info",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "Whatsapp"),
                    ("qq", "QQ"),
                    ("wechat", "Wechat"),
                    ("address", "Address"),
                ],
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
