# Generated by Django 4.2.7 on 2023-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_alter_contactinformation_link_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("whatsapp", "Whatsapp"),
                    ("qq", "QQ"),
                    ("wechat", "Wechat"),
                    ("address", "Address"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
