name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        TAG=$(date +%Y%m%d-%H%M%S)
        docker-compose --file docker-compose.prod.yml build
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Push the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push qrkks3/repository:${{ env.TAG }}
