name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set TAG variable
      id: set_tag
      run: echo "TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        TAG=${{ env.TAG }} docker-compose --file docker-compose.ci.yml build

    - name: Use TAG variable
      run: echo "Tag is ${{ env.TAG }}"

    # Add your Docker push steps here, using ${{ env.TAG }} to reference the tag
    
    - name: Push the Docker images
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push qrkks3/tradingweb:django-${{ env.TAG }}
        docker push qrkks3/tradingweb:nginx-${{ env.TAG }}

