name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set TAG variable
      run: |
        echo "TAG=$(date +%Y%m%d-%H%M%S -d @$(( $(date +%s) + 8*3600 )))" >> $GITHUB_ENV


    - name: Build the Docker image
      run: |
        echo "TZ=Asia/Shanghai" >> $GITHUB_ENV
        TAG=${{ env.TAG }} docker-compose --file docker-compose.ci.yml build

    - name: Use TAG variable
      run: echo "Tag is ${{ env.TAG }}"

    # Add your Docker push steps here, using ${{ env.TAG }} to reference the tag
    
    - name: Push the Docker images
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push qrkks3/tradingweb:django-${{ env.TAG }}
        docker push qrkks3/tradingweb:nginx-${{ env.TAG }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        sync: 'docker-compose.prod.yml'
        script: |
          cd /root

          # 设置环境变量
          export TAG=${{ env.TAG }}
          echo "Using TAG: $TAG"

          # 更新 .env 文件的逻辑
          KEY="TAG"
          VALUE="$TAG"
          FILE=".env"
          if grep -q "^${KEY}=" "$FILE"; then
              sed -i "s/^${KEY}=.*/${KEY}=${VALUE}/" "$FILE"
          else
              echo "${KEY}=${VALUE}" >> "$FILE"
          fi

          # Docker Compose 命令
          docker-compose down
          docker-compose pull
          docker-compose up -d
      env:
        TAG: ${{ env.TAG }}
