# Generated by Django 4.2.4 on 2023-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_options_remove_category_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="page_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
