# Generated by Django 4.2.4 on 2023-09-18 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_productimage_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
