# Generated by Django 4.2.4 on 2023-09-18 07:23

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_product_images_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to=products.models.product_image_path),
        ),
    ]
