# Generated by Django 4.2.4 on 2023-09-18 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="images",
            new_name="image",
        ),
    ]
