# Generated by Django 4.2.4 on 2023-09-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_product_options_alter_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-is_active", "-is_featured", "custom_order", "-name"]
            },
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
