# Generated by Django 4.2.4 on 2023-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_product_options_product_related_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="related_products",
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(blank=True, null=True, to="products.product"),
        ),
    ]
